networks:
  virtual:
    driver: bridge

services:
  database:
    image: mysql:debian
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password 
    ports:
      - 3307:3306
    volumes:
      - ./backend/db:/var/lib/mysql
    networks:
      - virtual
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      retries: 10
  backend:
    build: backend
    ports:
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000
    working_dir: /src
    volumes:
      - ./backend:/src
    depends_on: 
      database:
        condition: service_healthy
    networks:
      - virtual
  frontend:
    command: sh -c "npm install && npm start"
    build: 
      context: frontend
    ports:
      - 3000:3000
    networks:
      - virtual
    working_dir: /app
    volumes:
      - ./frontend:/app
    

volumes:
  db:
